### ISSUE TITLE
Filters against tax ID fields don't seem to work in 4.5.4

### ISSUE THREAD

**Issue by mbice** [microsoft-search/pnp-modern-search#1797]
**Version used**
4.5.4

**Describe the bug**
After testing the new 4.5.4 release, I noticed a change in how the filters are applied and they no longer seem to work for filters applied against taxId fields. From what I can tell there are multiple values with an "or" operator applied, and the last one is not hex encoded, which seems to be causing issues with the query.

**To Reproduce**
1. Map a refinable string to a taxId crawled property
2. Add filter mapped to your refinable string
3. Apply a filter on any of the terms
4. Notice one of the filter parameters is not hex encoded and search results are not properly filtered on your tag. In my test case, here's what the querystring looks like. eg:
?f=[{"filterName":"RefinableString52","values":[{"name":"People","value":"or(\"ǂǂ4c307c233035613936373866362d303066662d343434372d393333662d3731646631656535303964317c50656f706c65\",\"ǂǂ4750307c2335613936373866362d303066662d343434372d393333662d373164663165653530396431\",L0|#5a9678f6-00ff-4447-933f-71df1ee509d1)","operator":0,"disabled":false}],"operator":"or"}]
5. If you remove the un-encoded L0|# parameter, the query works correctly, but the filters web part has a selected tag bug where it's duplicated.

**Screenshots**
Here's what the filters web part looks like when I remove the L0|# portion of the querystring (where the search results are correct, but the rendering of the filters is wrong).

![image](https://user-images.githubusercontent.com/985283/152400779-92fe845c-0ae0-4028-9cc1-8dc100ba2379.png)

**Desktop (please complete the following information):**
 - Chrome, Edge (latest)

@FranckyC thoughts?

Thanks!

**Comment by FranckyC** [comment]
Hi @mbice , can you share the following to help us to debug:

- Managed property configuration in search schema
- Search Filters Web Part configuration
- The value of this managed property in debug mode in the Search Results

Thanks!

**Comment by mbice** [comment]
Hi,

**Managed property configuration**
- Field being used is multiple value taxonomy
- Mapped RefinableString52 to ows_taxId crawled property for this field.

**Search filters web part**
- Added RefinableString52
![image](https://user-images.githubusercontent.com/985283/152564138-310b1b89-e2fd-404b-89fe-7095870b9679.png)

**Search results**
- When I apply a filter for the term "People", the querystring looks like this: ?f=[{"filterName":"RefinableString52","values":[{"name":"People","value":"or(\"ǂǂ4c307c233035613936373866362d303066662d343434372d393333662d3731646631656535303964317c50656f706c65\",\"ǂǂ4750307c2335613936373866362d303066662d343434372d393333662d373164663165653530396431\",L0|#5a9678f6-00ff-4447-933f-71df1ee509d1)","operator":0,"disabled":false}],"operator":"or"}]#
- I see results for articles that are tagged with "People", but also articles that are not. One of the results that is tagged with people and correctly returned has a value for RefinableString52 in debug mode of this: "RefinableString52": "GP0|#5a9678f6-00ff-4447-933f-71df1ee509d1;L0|#05a9678f6-00ff-4447-933f-71df1ee509d1|People;GTSet|#84409741-041a-4fef-b334-11a2f98738e0"
- One of the results that is NOT tagged with "People" has a value in debug of this: "RefinableString52": "GP0|#bedf4c59-878c-421a-9a2b-c458f7baea07;L0|#0bedf4c59-878c-421a-9a2b-c458f7baea07|Technology;GTSet|#84409741-041a-4fef-b334-11a2f98738e0"

The RefinementFilters being passed through the postquery call looks like this (which I can verify does not return correct results when building it out using a search query tool): 

`"RefinementFilters": {
    "results": [
      "RefinableString52:or(\"ǂǂ4c307c233035613936373866362d303066662d343434372d393333662d3731646631656535303964317c50656f706c65\",\"ǂǂ4750307c2335613936373866362d303066662d343434372d393333662d373164663165653530396431\",L0|#5a9678f6-00ff-4447-933f-71df1ee509d1)"
    ]
  }`

Hope that helps. Let me know if you need more info.

Thanks!

**Comment by FranckyC** [comment]
@mbice so you mean you get results not tagged with 'People'? Given the values sent as refinement filters, that's technically not possible. What I suspect is the last OR property value is not enclosed with quotes causing wrong results. Can you try this fix using Search Query Tool?

**Comment by mbice** [comment]
@FranckyC I think it's both the fact it's not quote enclosed and that it's not hex encoded. If I put quotes around it, I still get weird search results. If I put quotes AND hex encode it, then search results are correct (e.g. instead of L0|#5a9678f6-00ff-4447-933f-71df1ee509d1, using "4c307c2335613936373866362d303066662d343434372d393333662d373164663165653530396431" works).

**Comment by FranckyC** [comment]
It is wanted that the value is not encoded actually. It is to cover this scenario: https://microsoft-search.github.io/pnp-modern-search/usage/search-filters/#use-indexed-property-bag-properties-with-taxonomy-values.

Did you try just with the quotes?

**Comment by mbice** [comment]
@FranckyC if I add quotes and URL encode the value (the "|" and "#" characters seem to create issues if they are not encoded), the query is still broken and the selected filters also don't look right.

e.g. the following URL:

`?f=[{"filterName":"RefinableString52","values":[{"name":"People","value":"or(\"ǂǂ4c307c233035613936373866362d303066662d343434372d393333662d3731646631656535303964317c50656f706c65\",\"ǂǂ4750307c2335613936373866362d303066662d343434372d393333662d373164663165653530396431\",\"L0%7C%235a9678f6-00ff-4447-933f-71df1ee509d1\")","operator":0,"disabled":false}],"operator":"or"}]
`

results in the following payload in the search query:

```
"RefinementFilters": {
    "results": [
      "RefinableString52:or(\"ǂǂ4c307c233035613936373866362d303066662d343434372d393333662d3731646631656535303964317c50656f706c65\",\"ǂǂ4750307c2335613936373866362d303066662d343434372d393333662d373164663165653530396431\",\"L0|#5a9678f6-00ff-4447-933f-71df1ee509d1\")"
    ]
  }
```

Which results in me seeing items not tagged with "People" and it breaks the filter display by showing two "People" checkboxes.

![image](https://user-images.githubusercontent.com/985283/153047796-b5cbc1c2-b3c5-46f6-9e54-7563a1c6ed3b.png)

**Comment by FranckyC** [comment]
@mbice And when you filter with this duplicated value, what results do you get and what is the `RefinableString52` value?

**Comment by wobba** [comment]
Can you try to instead of adding quotes do: `string("your string",linguistics=off)` for each of the three values?

**Comment by mbice** [comment]
@wobba yeah it seems that when using the or() operator on with the RefinementFilters object in the search query payload, it breaks if there's a mixture of functions (e.g. they either all need to be hex encoded OR they need to all use the string() function). The following refinement filters query works for me when I use string() on all the values instead of hex.

`RefinableString52:or(string("L0|#05a9678f6-00ff-4447-933f-71df1ee509d1|People"), string("GP0|#5a9678f6-00ff-4447-933f-71df1ee509d1"), string("L0|#5a9678f6-00ff-4447-933f-71df1ee509d1"))`

If I try and mix and match them (e.g. hex encode the first two parameters and use string() on the last one, it breaks the query).

**Comment by FranckyC** [comment]
@mbice interesting behavior :/ I will do the update to the code then including `string()` operator. Thank you for the time you spent to test this behavior.

**Comment by FranckyC** [comment]
Should be fixed by PR #1818 if you have the chance to test. I'll close it for now. Thanks!

**Comment by mbice** [comment]
@FranckyC thanks - I just tested it out latest off develop branch and I think there's still an issue. I think, for these tax ID refinables, that if the string() function is used in the RefinementFilters that it won't work with the hex encoded values. When I was testing with the search query tool, I found that with an or() operator all values had to use string() function or none of them. If string() was used, I needed to put in the string value of the GUID, not the hex encoded refinement token.. Not totally sure why, but that's what seemed to work.

**Comment by FranckyC** [comment]
@mbice  can you try with the latest `develop` branch? I've made several tests and jsut enclosing the text value with either quotes or string() operator works for all cases.

**Comment by mbice** [comment]
Hi @FranckyC,

Sorry for the delayed reply. This still seems to have issues for me. From what I can tell, if I include a string() operator and a refinement token value in the OR query, it returns a bunch more stuff. If I remove just the string() operator, it returns articles correctly. Somehow mixing and matching token and string values in the same refinement filter doesn't work (even through the search query tool).
