### ISSUE TITLE
Custom handlebar helpers / external script

### ISSUE THREAD

**Issue by Jeroen00** [microsoft-search/pnp-modern-search#182]
It doesn't seem possible in the Search Results web part to load any custom handlebars helpers or custom JavaScript, is that correct? Is there a reason for this? And is there a workaround? Or can it be added as a feature in the same way as the React Content Query Web Part? Thanks!

**Comment by FranckyC** [comment]
Hi @Jeroen00. You're right, it is not possible to create custom helpers for now. Maybe this feature will be integrated to the extensibility later bu but planned yet. For the Javascript, the reason is mainly about security and to avoid XSS attacks.

**Comment by FranckyC** [comment]
If youd need to write logic, you can still create your own web component. See https://microsoft-search.github.io/pnp-modern-search/search-extensibility-library/getting-started/#create-a-custom-web-component

**Comment by Jeroen00** [comment]
@FranckyC Thanks for your response. I thought I had a solution by adding an onclick call to my JavaScript function. This worked fine in version 3.11.0.3 but with the latest version (3.12.1.0) this also seems to be stripped from the template? Is it correct this was changed and why? I have control over what I put in the template so I do not see why I shouldn't be allowed to add an onclick event??

**Comment by wobba** [comment]
This is correct behavior as we want to prevent html/css/script injection. You might have control, but we want to prevent misuse by someone with edit rights on a page.

**Comment by wobba** [comment]
Script injection in href tag fixed in the dev branch with #2957

**Comment by Nevinia210** [comment]
@wobba  - Is there please some update on this or it is still not working on 4.9?

**Comment by wobba** [comment]
@Nevinia210  v4.9 has re-added the script blocking - as it should not have been enabled in previous versions.
